In [1]:
from core.youtube_download import download_youtube_audio
from core.blob_storage import WavToBlobUploader, generate_sas_token
from core.azure_speech_to_text import TranscriptionQueue
from config import (
        AZURE_STORAGE_AUDIO_CONTAINER_NAME, 
        AZURE_STORAGE_CONNECTION_STRING, 
        AZURE_STORAGE_TRANSCRIPTIONS_CONTAINER_NAME, 
        AZURE_SPEECH_KEY,
        AZURE_SPEECH_REGION,
        DATA_FOLDER
)


import pandas as pd

In [2]:
df_urls = pd.read_csv(f'{DATA_FOLDER}/minutagem_audiencias.csv')

In [3]:
df_urls.head()

,Tipo,Subprefeitura,Data,Fala dos Municipes - Início,Fala dos Munícipes - Fim,Vídeo,Fala do Vereador 1 - Início,Fala do Vereador 1 - Fim,Fala do Vereador 2 - Início,Fala do Vereador 2 - Fim,Fala do Vereador 3 - Início,Fala do Vereador 3 - Fim,Unnamed: 12
0,Geral,Audiência Pública Geral,7/4/2025,1:19:27,2:26:50,https://youtu.be/NA72Vx4HQ_A?si=gPYUKo2Uu6K9xMXr,29:22 - Renata Falzoni,36:28 - Renata Falzoni,57:24 - Marina Bragante,1:08:11- Marina Bragante,01:10:08 - Nabil Bonduki,1:17:59 - Nabil Bonduki,NaN
1,Temática,Audiência Pública Temática 1: Universo SP,8/4/2025,1:18:40,2:25:46,https://youtu.be/ZE641NDeXik?si=91RkiRFpCm4uCphn,13:38 - Marina Bragante,18:10 - Marina Bragante,1:22:53 - Nabil Bonduki,1:30:26 - Nabil Bonduki,-,NaN,NaN
2,Temática,Audiência Pública Temática 2: Viver São Paulo,9/4/2025,1:05:06,1:41:00,https://youtu.be/xI7X14megCg?si=oijX5Smsrjptv5mg,-,NaN,-,NaN,-,NaN,NaN
3,Temática,Audiência Pública Temática 3: Cidade Empreende...,10/4/2025,1:00:37,1:12:21,https://youtu.be/Hlu9rDeirSo?si=h-uZ8sfnJikZKXQQ,-,NaN,-,NaN,-,NaN,NaN
4,Regional,Vila Maria/Vila Guilherme,14/04/2025,1:45:25,2:05:33,https://youtu.be/s7ssnh6g9-0?si=o5ex6sVEul7BRUEb,-,NaN,-,NaN,-,NaN,NaN

In [4]:
df_urls.tail()

,Tipo,Subprefeitura,Data,Fala dos Municipes - Início,Fala dos Munícipes - Fim,Vídeo,Fala do Vereador 1 - Início,Fala do Vereador 1 - Fim,Fala do Vereador 2 - Início,Fala do Vereador 2 - Fim,Fala do Vereador 3 - Início,Fala do Vereador 3 - Fim,Unnamed: 12
358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_urls = df_urls.dropna(how='all')

In [6]:
df_urls.columns

Index(['Tipo', 'Subprefeitura', 'Data', 'Fala dos Municipes - Início',
       'Fala dos Munícipes - Fim', 'Vídeo', 'Fala do Vereador 1 - Início',
       'Fala do Vereador 1 - Fim', 'Fala do Vereador 2 - Início',
       'Fala do Vereador 2 - Fim', 'Fala do Vereador 3  - Início',
       'Fala do Vereador 3  - Fim', 'Unnamed: 12'],
      dtype='object')

In [7]:
df_urls.shape

(36, 13)

In [8]:
df_urls['init_time'] = df_urls['Fala dos Municipes - Início'].str.zfill(8)
df_urls['end_time'] = df_urls['Fala dos Munícipes - Fim'].str.zfill(8)

In [9]:
from unidecode import unidecode

urls = [
    {
        'id' : i,
        'nome' : unidecode(row['Subprefeitura'].strip().lower().replace(' ', '_').replace('/', '_')),
        'url': row['Vídeo'].strip(),
        'init_time': row['init_time'].strip(),
        'end_time': row['end_time'].strip(),
    }
    for i, row in df_urls.iterrows()
]

In [10]:
urls

[{'id': 0,
  'nome': 'audiencia_publica_geral',
  'url': 'https://youtu.be/NA72Vx4HQ_A?si=gPYUKo2Uu6K9xMXr',
  'init_time': '01:19:27',
  'end_time': '02:26:50'},
 {'id': 1,
  'nome': 'audiencia_publica_tematica_1:_universo_sp',
  'url': 'https://youtu.be/ZE641NDeXik?si=91RkiRFpCm4uCphn',
  'init_time': '01:18:40',
  'end_time': '02:25:46'},
 {'id': 2,
  'nome': 'audiencia_publica_tematica_2:_viver_sao_paulo',
  'url': 'https://youtu.be/xI7X14megCg?si=oijX5Smsrjptv5mg',
  'init_time': '01:05:06',
  'end_time': '01:41:00'},
 {'id': 3,
  'nome': 'audiencia_publica_tematica_3:_cidade_empreendedora_e_capital_do_futuro',
  'url': 'https://youtu.be/Hlu9rDeirSo?si=h-uZ8sfnJikZKXQQ',
  'init_time': '01:00:37',
  'end_time': '01:12:21'},
 {'id': 4,
  'nome': 'vila_maria_vila_guilherme',
  'url': 'https://youtu.be/s7ssnh6g9-0?si=o5ex6sVEul7BRUEb',
  'init_time': '01:45:25',
  'end_time': '02:05:33'},
 {'id': 5,
  'nome': 'lapa',
  'url': 'https://youtu.be/Hozs3pN_Bq4?si=rox1nogPTf-pbUJT',
  'init_time': '01:41:06',
  'end_time': '02:05:26'},
 {'id': 6,
  'nome': 'campo_limpo',
  'url': 'https://youtu.be/Yw1i08umwh8?si=t_BDuSOf2NASkrEf',
  'init_time': '01:28:03',
  'end_time': '01:47:27'},
 {'id': 7,
  'nome': 'ermelino_matarazzo',
  'url': 'https://youtu.be/qwZpPdrX7Tg?si=-NzgjC_bsZgmYHdv',
  'init_time': '01:31:43',
  'end_time': '02:00:50'},
 {'id': 8,
  'nome': 'aricanduva_formosa_carrao',
  'url': 'https://youtu.be/GYqvWjI1uxs?si=IvVT94ELJUh4siVG',
  'init_time': '01:57:59',
  'end_time': '02:28:10'},
 {'id': 9,
  'nome': 'pinheiros',
  'url': 'https://youtu.be/XeCnd1gVdGg?si=Gvj3gcrDt_5W-o-f',
  'init_time': '02:03:27',
  'end_time': '02:25:17'},
 {'id': 10,
  'nome': 'santana_tucuruvi',
  'url': 'https://youtu.be/7jsMPWnrJwc?si=d1NsmxFYWV-fXum9',
  'init_time': '01:34:17',
  'end_time': '02:18:09'},
 {'id': 11,
  'nome': 'capela_do_socorro',
  'url': 'https://youtu.be/VggjIBklqf8?si=xBctw0e32_PHjLge',
  'init_time': '01:40:35',
  'end_time': '01:58:05'},
 {'id': 12,
  'nome': 'cidade_tiradentes',
  'url': 'https://youtu.be/IuVW4pcKtaw?si=BM37auXnXAkVmpUR',
  'init_time': '02:03:04',
  'end_time': '02:53:50'},
 {'id': 13,
  'nome': 'perus',
  'url': 'https://youtu.be/9WK0pAFWym4?si=-7_TU32xogFRifw8',
  'init_time': '01:41:50',
  'end_time': '02:21:04'},
 {'id': 14,
  'nome': 'cidade_ademar',
  'url': 'https://youtu.be/U6f57tFWW-c?si=vrChQhY_l8VPfSka',
  'init_time': '01:48:17',
  'end_time': '02:33:57'},
 {'id': 15,
  'nome': 'butanta',
  'url': 'https://youtu.be/pdZSdpTfZQg?si=FhJf0qR9F6U-HsMV',
  'init_time': '01:02:54',
  'end_time': '01:13:27'},
 {'id': 16,
  'nome': 'se',
  'url': 'https://youtu.be/nNL7uND3b_A?si=AVag4wQxYD6O5O1A',
  'init_time': '01:20:52',
  'end_time': '01:43:29'},
 {'id': 17,
  'nome': 'pirituba_jaragua',
  'url': 'https://youtu.be/r2Co7xHF6bg?si=VkT1cejPbIie7Ned',
  'init_time': '01:42:43',
  'end_time': '02:20:00'},
 {'id': 18,
  'nome': 'vila_mariana',
  'url': 'https://youtu.be/tyWIcjeW8gg?si=l1PJOkoueShUK6SE',
  'init_time': '01:19:26',
  'end_time': '3:06:23'},
 {'id': 19,
  'nome': 'jacana_tremembe',
  'url': 'https://youtu.be/HBf8oWzQKS0?si=QHZnpA8Jj5EDzdlZ',
  'init_time': '01:49:32',
  'end_time': '02:44:41'},
 {'id': 20,
  'nome': 'guaianases',
  'url': 'https://youtu.be/f6GwHgh4UlA?si=68Wtn8QedwP_kkAi',
  'init_time': '01:25:56',
  'end_time': '02:29:33'},
 {'id': 21,
  'nome': 'santo_amaro',
  'url': 'https://youtu.be/_pYh7cvPCtQ?si=uNN9jSMfuKVBhrXC',
  'init_time': '01:21:11',
  'end_time': '01:44:30'},
 {'id': 22,
  'nome': 'casa_verde_cachoeirinha',
  'url': 'https://youtu.be/5TKwyE78zd4?si=zpJXvR5DV9TJqwA1',
  'init_time': '01:38:04',
  'end_time': '02:51:30'},
 {'id': 23,
  'nome': 'itaquera',
  'url': 'https://youtu.be/FZQcLDobotc?si=-5Z48gKqn8THGk04',
  'init_time': '01:29:05',
  'end_time': '02:50:52'},
 {'id': 24,
  'nome': 'jabaquara',
  'url': 'https://youtu.be/QN1IyLeUniM?si=plEN-iyia_vjPdDN',
  'init_time': '01:24:18',
  'end_time': '01:59:24'},
 {'id': 25,
  'nome': 'itaim_paulista',
  'url': 'https://youtu.be/GNikDX8H_9M?si=89z9d9VerWu3LM83',
  'init_time': '01:16:54',
  'end_time': '01:52:55'},
 {'id': 26,
  'nome': 'ipiranga',
  'url': 'https://youtu.be/M9EtMISTU6c?si=ybnypxfVLqYrPG5A',
  'init_time': '01:25:04',
  'end_time': '01:57:33'},
 {'id': 27,
  'nome': 'parelheiros',
  'url': 'https://youtu.be/mhVoDpoEZTc?si=2xHv6_bcAKybwzhu',
  'init_time': '01:22:40',
  'end_time': '02:19:11'},
 {'id': 28,
  'nome': 'freguesia_brasilandia',
  'url': 'https://youtu.be/LM0AlsAXccM?si=bGkrHsX5p2o42e2z',
  'init_time': '01:28:23',
  'end_time': '02:36:14'},
 {'id': 29,
  'nome': "m'boi_mirim",
  'url': 'https://youtu.be/QDW_PaP6kXo?si=xmAE9H01QUJZhg0Z',
  'init_time': '01:28:49',
  'end_time': '02:28:05'},
 {'id': 30,
  'nome': 'mooca',
  'url': 'https://youtu.be/Z69PLWdKZJk?si=u5NkaTTNgCE54YSl',
  'init_time': '01:48:38',
  'end_time': '02:06:52'},
 {'id': 31,
  'nome': 'sapopemba',
  'url': 'https://youtu.be/GeGi28cjhqY?si=Ue_lZ4Q60vReX4RR',
  'init_time': '01:24:21',
  'end_time': '02:22:47'},
 {'id': 32,
  'nome': 'vila_prudente',
  'url': 'https://youtu.be/Vt7yUPD-Zng?si=nTG-bCcSs6Awccd0',
  'init_time': '01:38:45',
  'end_time': '02:36:46'},
 {'id': 33,
  'nome': 'penha',
  'url': 'https://youtu.be/APDLszE-PSc?si=56GAj4fXUpchh2Lx',
  'init_time': '01:28:13',
  'end_time': '02:08:05'},
 {'id': 34,
  'nome': 'sao_mateus',
  'url': 'https://youtu.be/zXsFmWKXdRw?si=4GfhLD-23bX_dcYA',
  'init_time': '01:34:49',
  'end_time': '02:43:01'},
 {'id': 35,
  'nome': 'sao_miguel',
  'url': 'https://youtu.be/StVKCx0bWuY?si=PsDA7876G1PlUCNi',
  'init_time': '01:41:44',
  'end_time': '02:47:39'}]

In [11]:
import time
import random
import os
from config import WAV_FOLDER

for url in urls:
    if os.path.exists(f'{WAV_FOLDER}/{url["nome"]}.wav'):
        print(f'Audio {url["nome"]} already exists')
        continue
    print(f'Downloading audio for {url["nome"]}')
    download_youtube_audio(url['url'],
                        url['nome'] + '.wav',
                        url['init_time'],
                        url['end_time']
                        )
    time.sleep(random.randint(1, 7))

Audio audiencia_publica_geral already exists
Audio audiencia_publica_tematica_1:_universo_sp already exists
Audio audiencia_publica_tematica_2:_viver_sao_paulo already exists
Audio audiencia_publica_tematica_3:_cidade_empreendedora_e_capital_do_futuro already exists
Audio vila_maria_vila_guilherme already exists
Audio lapa already exists
Audio campo_limpo already exists
Audio ermelino_matarazzo already exists
Audio aricanduva_formosa_carrao already exists
Audio pinheiros already exists
Audio santana_tucuruvi already exists
Audio capela_do_socorro already exists
Audio cidade_tiradentes already exists
Audio perus already exists
Audio cidade_ademar already exists
Audio butanta already exists
Audio se already exists
Audio pirituba_jaragua already exists
Audio vila_mariana already exists
Audio jacana_tremembe already exists
Audio guaianases already exists
Audio santo_amaro already exists
Audio casa_verde_cachoeirinha already exists
Audio itaquera already exists
Audio jabaquara already exists
Audio itaim_paulista already exists
Audio ipiranga already exists
Audio parelheiros already exists
Audio freguesia_brasilandia already exists
Audio m'boi_mirim already exists
Audio mooca already exists
Audio sapopemba already exists
Audio vila_prudente already exists
Audio penha already exists
Audio sao_mateus already exists
Audio sao_miguel already exists

In [12]:
blob = WavToBlobUploader()

In [13]:
import json

with open(f'{DATA_FOLDER}/urls_cache.json', 'r', encoding='utf-8') as f:
    urls = json.load(f)

In [14]:
for url in urls:

    if 'sas_token' in url and url['sas_token']:
        print(f'Audio {url["nome"]} already uploaded')
        continue
    file = f'{WAV_FOLDER}/{url["nome"]}_clip.wav'

    if not os.path.exists(file):
        raise RuntimeError(f'Audio {url["nome"]} does not exist')
    
    print(f'Uploading {url["nome"]} to blob storage')
    
    audio_file_token = blob(file)

    url['sas_token'] = audio_file_token

Audio audiencia_publica_geral already uploaded
Audio audiencia_publica_tematica_1:_universo_sp already uploaded
Audio audiencia_publica_tematica_2:_viver_sao_paulo already uploaded
Audio audiencia_publica_tematica_3:_cidade_empreendedora_e_capital_do_futuro already uploaded
Audio vila_maria_vila_guilherme already uploaded
Audio lapa already uploaded
Audio campo_limpo already uploaded
Audio ermelino_matarazzo already uploaded
Audio aricanduva_formosa_carrao already uploaded
Audio pinheiros already uploaded
Audio santana_tucuruvi already uploaded
Audio capela_do_socorro already uploaded
Audio cidade_tiradentes already uploaded
Audio perus already uploaded
Audio cidade_ademar already uploaded
Audio butanta already uploaded
Audio se already uploaded
Audio pirituba_jaragua already uploaded
Audio vila_mariana already uploaded
Audio jacana_tremembe already uploaded
Audio guaianases already uploaded
Audio santo_amaro already uploaded
Audio casa_verde_cachoeirinha already uploaded
Audio itaquera already uploaded
Audio jabaquara already uploaded
Audio itaim_paulista already uploaded
Audio ipiranga already uploaded
Audio parelheiros already uploaded
Audio freguesia_brasilandia already uploaded
Audio m'boi_mirim already uploaded
Audio mooca already uploaded
Audio sapopemba already uploaded
Audio vila_prudente already uploaded
Audio penha already uploaded
Audio sao_mateus already uploaded
Audio sao_miguel already uploaded

In [15]:
import json

with open(f'{DATA_FOLDER}/urls_cache.json', 'w', encoding='utf-8') as f:
    json.dump(urls, f, ensure_ascii=False, indent=2)

In [16]:
container_token =generate_sas_token(AZURE_STORAGE_TRANSCRIPTIONS_CONTAINER_NAME, container_token=True)

In [17]:
import importlib

import core.azure_speech_to_text.transcription_queue
importlib.reload(core.azure_speech_to_text.transcription_queue)

transcritor = core.azure_speech_to_text.transcription_queue.TranscriptionQueue(container_token)

fui reimportado

In [18]:
transcritor.iniciar_transcricoes([url['sas_token'] for url in urls])

🚀 Iniciando jobs de transcrição...
Posting to Azure API: https://brazilsouth.api.cognitive.microsoft.com/speechtotext/v3.2/transcriptions
{'contentUrls': ['https://transcricoespdm.blob.core.windows.net/audios/audiencia_publica_geral_clip.wav?se=2025-05-20T03%3A09%3A24Z&sp=r&sv=2025-05-05&sr=b&sig=n3FuY5OcFG9SvXUz3UeI1%2Bya/h61Njud%2BkTmyNJgNJQ%3D', 'https://transcricoespdm.blob.core.windows.net/audios/audiencia_publica_tematica_1:_universo_sp_clip.wav?se=2025-05-20T03%3A10%3A26Z&sp=r&sv=2025-05-05&sr=b&sig=qN2JmBHu1NzhdGkb6UbzD5%2Bp4CKPLb1LaOJtTHGqeMs%3D', 'https://transcricoespdm.blob.core.windows.net/audios/audiencia_publica_tematica_2:_viver_sao_paulo_clip.wav?se=2025-05-20T03%3A10%3A59Z&sp=r&sv=2025-05-05&sr=b&sig=5h/T506LggQsoYBZ1EeV3p8y75ZEVARcVHBe3pv4I6I%3D', 'https://transcricoespdm.blob.core.windows.net/audios/audiencia_publica_tematica_3:_cidade_empreendedora_e_capital_do_futuro_clip.wav?se=2025-05-20T03%3A11%3A10Z&sp=r&sv=2025-05-05&sr=b&sig=OUJl/beuwwc3Bxrv0UTjazCHRD%2Bvdfm1kiOb5gRfDYo%3D', 'https://transcricoespdm.blob.core.windows.net/audios/vila_maria_vila_guilherme_clip.wav?se=2025-05-20T03%3A11%3A28Z&sp=r&sv=2025-05-05&sr=b&sig=2yMqRUwSGFNlJ1EWfLD813X0PY/WqH0ZwjDIQ7sSDJs%3D', 'https://transcricoespdm.blob.core.windows.net/audios/lapa_clip.wav?se=2025-05-20T03%3A11%3A49Z&sp=r&sv=2025-05-05&sr=b&sig=mrNiWfAQpTj9%2Bdzwq56HLJSjKWbjz8kST8PwL1X6/l8%3D', 'https://transcricoespdm.blob.core.windows.net/audios/campo_limpo_clip.wav?se=2025-05-20T03%3A12%3A07Z&sp=r&sv=2025-05-05&sr=b&sig=tjQgNBGyOwoIrv0sk/DoOLe/GEtIzCffP2tM4mzeIGI%3D', 'https://transcricoespdm.blob.core.windows.net/audios/ermelino_matarazzo_clip.wav?se=2025-05-20T03%3A12%3A33Z&sp=r&sv=2025-05-05&sr=b&sig=xpk04W%2BrzjHVvx8u1I6dPJCiirX2JLDMuizhnUMJciQ%3D', 'https://transcricoespdm.blob.core.windows.net/audios/aricanduva_formosa_carrao_clip.wav?se=2025-05-20T03%3A13%3A01Z&sp=r&sv=2025-05-05&sr=b&sig=C%2BD3COCiZaxDyYAOrw7Q4frEbOUe1Ux0rz3dlxDZarU%3D', 'https://transcricoespdm.blob.core.windows.net/audios/pinheiros_clip.wav?se=2025-05-20T03%3A13%3A21Z&sp=r&sv=2025-05-05&sr=b&sig=xSrzQjyvA/0J%2BFJu07GBfPXun1jamI93dVdIx8BM2v0%3D', 'https://transcricoespdm.blob.core.windows.net/audios/santana_tucuruvi_clip.wav?se=2025-05-20T03%3A14%3A07Z&sp=r&sv=2025-05-05&sr=b&sig=8MeaqHhpp8KO6gfY1yhBpzJvl%2BIKM5RH3AkPkq1flIw%3D', 'https://transcricoespdm.blob.core.windows.net/audios/capela_do_socorro_clip.wav?se=2025-05-20T03%3A14%3A22Z&sp=r&sv=2025-05-05&sr=b&sig=TLPNsvKGkmR3j4t/zRgQu58N4rvfzamATT%2B9aViu%2B%2Bc%3D', 'https://transcricoespdm.blob.core.windows.net/audios/cidade_tiradentes_clip.wav?se=2025-05-20T03%3A15%3A08Z&sp=r&sv=2025-05-05&sr=b&sig=2K2a4vHNxJRNJ9Fc2QY/os9o3jgE0kcNx8qbCCjVPDk%3D', 'https://transcricoespdm.blob.core.windows.net/audios/perus_clip.wav?se=2025-05-20T03%3A15%3A41Z&sp=r&sv=2025-05-05&sr=b&sig=lq/gukuhPt8Ucvn/mnjYhdOqg1pelOem/7rLTkeV85o%3D', 'https://transcricoespdm.blob.core.windows.net/audios/cidade_ademar_clip.wav?se=2025-05-20T03%3A16%3A18Z&sp=r&sv=2025-05-05&sr=b&sig=UHkBx8VtljTY3GmdRdEx6y6lrBb1luyeBJwkYAJm6Fo%3D', 'https://transcricoespdm.blob.core.windows.net/audios/butanta_clip.wav?se=2025-05-20T03%3A16%3A26Z&sp=r&sv=2025-05-05&sr=b&sig=r4tMVu8%2BV9voiTazJ3bgHzigEAFHuTGSvnFpS3qKKIM%3D', 'https://transcricoespdm.blob.core.windows.net/audios/se_clip.wav?se=2025-05-20T03%3A16%3A46Z&sp=r&sv=2025-05-05&sr=b&sig=Mgymd/HsjnNe2LAOBchgZCf3wPTAXW6YeGQus2Ugwd4%3D', 'https://transcricoespdm.blob.core.windows.net/audios/pirituba_jaragua_clip.wav?se=2025-05-20T03%3A17%3A18Z&sp=r&sv=2025-05-05&sr=b&sig=nN0GmKORsqsdL6bRPL7j0hvY4VYxX3GxdXB3HOl5rUs%3D', 'https://transcricoespdm.blob.core.windows.net/audios/vila_mariana_clip.wav?se=2025-05-20T03%3A18%3A59Z&sp=r&sv=2025-05-05&sr=b&sig=kEzsViQA/JOzGMDo/keT6JEmLl6W3YrL9OsTFPRN7KA%3D', 'https://transcricoespdm.blob.core.windows.net/audios/jacana_tremembe_clip.wav?se=2025-05-20T03%3A19%3A48Z&sp=r&sv=2025-05-05&sr=b&sig=F6H4b9vqA71KrrR0F07ejSJsGbLSqnodT%2BsRS4W2XNw%3D', 'https://transcricoespdm.blob.core.windows.net/audios/guaianases_clip.wav?se=2025-05-20T03%3A20%3A41Z&sp=r&sv=2025-05-05&sr=b&sig=e6V3yh4Bd9p2/dCM8DhcShTB1ZtXSr%2Bk9KkGxGiDbds%3D', 'https://transcricoespdm.blob.core.windows.net/audios/santo_amaro_clip.wav?se=2025-05-20T03%3A21%3A01Z&sp=r&sv=2025-05-05&sr=b&sig=NJkAEw1OVZ1iMaL1bt40qSVc7lxQlqEb%2BkGOtOfxS7o%3D', 'https://transcricoespdm.blob.core.windows.net/audios/casa_verde_cachoeirinha_clip.wav?se=2025-05-20T03%3A22%3A03Z&sp=r&sv=2025-05-05&sr=b&sig=e5Og4Znkc7Lxiu3Y5m%2BMgZF46eZsmtbFpjMljJOBI68%3D', 'https://transcricoespdm.blob.core.windows.net/audios/itaquera_clip.wav?se=2025-05-20T03%3A23%3A14Z&sp=r&sv=2025-05-05&sr=b&sig=qgQ0Re8YjQ%2BMyQ23f18SnTNQdvCiChvHDFEdvGFlbfQ%3D', 'https://transcricoespdm.blob.core.windows.net/audios/jabaquara_clip.wav?se=2025-05-20T03%3A23%3A45Z&sp=r&sv=2025-05-05&sr=b&sig=tG6qYET1J%2BrNftGuyXwzPXS6HTM2tp2eSuHBeud6G/M%3D', 'https://transcricoespdm.blob.core.windows.net/audios/itaim_paulista_clip.wav?se=2025-05-20T03%3A24%3A22Z&sp=r&sv=2025-05-05&sr=b&sig=24DQI5ZtejHlTqhUzHGHjzg7tFvKvovL4y5zYsltp0c%3D', 'https://transcricoespdm.blob.core.windows.net/audios/ipiranga_clip.wav?se=2025-05-20T03%3A24%3A51Z&sp=r&sv=2025-05-05&sr=b&sig=N%2BbGDmyuRLrcbXyQAwbBgT/KH4zuWTZ5S9nfubg7r9o%3D', 'https://transcricoespdm.blob.core.windows.net/audios/parelheiros_clip.wav?se=2025-05-20T03%3A25%3A39Z&sp=r&sv=2025-05-05&sr=b&sig=sSiBCEzMvXoC4cPLYwlpG2ynusU7oW2EDk8uRy5ubtg%3D', 'https://transcricoespdm.blob.core.windows.net/audios/freguesia_brasilandia_clip.wav?se=2025-05-20T03%3A26%3A37Z&sp=r&sv=2025-05-05&sr=b&sig=lB0p0VT4whVXfJ5nsq%2BGkt4eusYaTG6/PZxnGJybU9s%3D', "https://transcricoespdm.blob.core.windows.net/audios/m'boi_mirim_clip.wav?se=2025-05-20T03%3A27%3A25Z&sp=r&sv=2025-05-05&sr=b&sig=W/JjAai/6jLTK%2B3Wz4cfN6Xa%2BR3VFg3DSvRzrA21%2BoI%3D", 'https://transcricoespdm.blob.core.windows.net/audios/mooca_clip.wav?se=2025-05-20T03%3A27%3A41Z&sp=r&sv=2025-05-05&sr=b&sig=2IcuHK2rWzCBbi5RWdcTMJA1Ig8JO%2Bzls1ZiBW1yZtI%3D', 'https://transcricoespdm.blob.core.windows.net/audios/sapopemba_clip.wav?se=2025-05-20T03%3A28%3A29Z&sp=r&sv=2025-05-05&sr=b&sig=jf4naWGGGcUXx%2BQ52P24wZNFXVTobT9lKJBn5jc8754%3D', 'https://transcricoespdm.blob.core.windows.net/audios/vila_prudente_clip.wav?se=2025-05-20T03%3A29%3A20Z&sp=r&sv=2025-05-05&sr=b&sig=PfRWzVAJdaHZeVcj4WM0Jbo4UrLguGbdwwGdO7KqYMc%3D', 'https://transcricoespdm.blob.core.windows.net/audios/penha_clip.wav?se=2025-05-20T03%3A30%3A00Z&sp=r&sv=2025-05-05&sr=b&sig=tIHB9asjhHsxkdaB/A/%2BvTnv%2BeOxCuJ69MElI8pk1kY%3D', 'https://transcricoespdm.blob.core.windows.net/audios/sao_mateus_clip.wav?se=2025-05-20T03%3A30%3A59Z&sp=r&sv=2025-05-05&sr=b&sig=7s8wjQk0QBW2Y2PV6qfe7/GHj1ueSa8/8hjXqCeznec%3D', 'https://transcricoespdm.blob.core.windows.net/audios/sao_miguel_clip.wav?se=2025-05-20T03%3A31%3A57Z&sp=r&sv=2025-05-05&sr=b&sig=c4p3equGm1vKmj77I1nbMxSzAGRzGMgjyOYQhobsvnY%3D'], 'locale': 'pt-BR', 'displayName': 'batch_transcription', 'properties': {'wordLevelTimestampsEnabled': False, 'punctuationMode': 'DictatedAndAutomatic', 'profanityFilterMode': 'None', 'destinationContainerUrl': 'https://transcricoespdm.blob.core.windows.net/transcricoes?se=2025-05-20T03%3A47%3A04Z&sp=racwle&sv=2025-05-05&sr=c&sig=JE7AESis4/RrVRmiH51gkCwTyKMwc4kWMiGFoPcuVLY%3D'}}
Job initiated successfully.
🔁 Job iniciado para ['https://transcricoespdm.blob.core.windows.net/audios/audiencia_publica_geral_clip.wav?se=2025-05-20T03%3A09%3A24Z&sp=r&sv=2025-05-05&sr=b&sig=n3FuY5OcFG9SvXUz3UeI1%2Bya/h61Njud%2BkTmyNJgNJQ%3D', 'https://transcricoespdm.blob.core.windows.net/audios/audiencia_publica_tematica_1:_universo_sp_clip.wav?se=2025-05-20T03%3A10%3A26Z&sp=r&sv=2025-05-05&sr=b&sig=qN2JmBHu1NzhdGkb6UbzD5%2Bp4CKPLb1LaOJtTHGqeMs%3D', 'https://transcricoespdm.blob.core.windows.net/audios/audiencia_publica_tematica_2:_viver_sao_paulo_clip.wav?se=2025-05-20T03%3A10%3A59Z&sp=r&sv=2025-05-05&sr=b&sig=5h/T506LggQsoYBZ1EeV3p8y75ZEVARcVHBe3pv4I6I%3D', 'https://transcricoespdm.blob.core.windows.net/audios/audiencia_publica_tematica_3:_cidade_empreendedora_e_capital_do_futuro_clip.wav?se=2025-05-20T03%3A11%3A10Z&sp=r&sv=2025-05-05&sr=b&sig=OUJl/beuwwc3Bxrv0UTjazCHRD%2Bvdfm1kiOb5gRfDYo%3D', 'https://transcricoespdm.blob.core.windows.net/audios/vila_maria_vila_guilherme_clip.wav?se=2025-05-20T03%3A11%3A28Z&sp=r&sv=2025-05-05&sr=b&sig=2yMqRUwSGFNlJ1EWfLD813X0PY/WqH0ZwjDIQ7sSDJs%3D', 'https://transcricoespdm.blob.core.windows.net/audios/lapa_clip.wav?se=2025-05-20T03%3A11%3A49Z&sp=r&sv=2025-05-05&sr=b&sig=mrNiWfAQpTj9%2Bdzwq56HLJSjKWbjz8kST8PwL1X6/l8%3D', 'https://transcricoespdm.blob.core.windows.net/audios/campo_limpo_clip.wav?se=2025-05-20T03%3A12%3A07Z&sp=r&sv=2025-05-05&sr=b&sig=tjQgNBGyOwoIrv0sk/DoOLe/GEtIzCffP2tM4mzeIGI%3D', 'https://transcricoespdm.blob.core.windows.net/audios/ermelino_matarazzo_clip.wav?se=2025-05-20T03%3A12%3A33Z&sp=r&sv=2025-05-05&sr=b&sig=xpk04W%2BrzjHVvx8u1I6dPJCiirX2JLDMuizhnUMJciQ%3D', 'https://transcricoespdm.blob.core.windows.net/audios/aricanduva_formosa_carrao_clip.wav?se=2025-05-20T03%3A13%3A01Z&sp=r&sv=2025-05-05&sr=b&sig=C%2BD3COCiZaxDyYAOrw7Q4frEbOUe1Ux0rz3dlxDZarU%3D', 'https://transcricoespdm.blob.core.windows.net/audios/pinheiros_clip.wav?se=2025-05-20T03%3A13%3A21Z&sp=r&sv=2025-05-05&sr=b&sig=xSrzQjyvA/0J%2BFJu07GBfPXun1jamI93dVdIx8BM2v0%3D', 'https://transcricoespdm.blob.core.windows.net/audios/santana_tucuruvi_clip.wav?se=2025-05-20T03%3A14%3A07Z&sp=r&sv=2025-05-05&sr=b&sig=8MeaqHhpp8KO6gfY1yhBpzJvl%2BIKM5RH3AkPkq1flIw%3D', 'https://transcricoespdm.blob.core.windows.net/audios/capela_do_socorro_clip.wav?se=2025-05-20T03%3A14%3A22Z&sp=r&sv=2025-05-05&sr=b&sig=TLPNsvKGkmR3j4t/zRgQu58N4rvfzamATT%2B9aViu%2B%2Bc%3D', 'https://transcricoespdm.blob.core.windows.net/audios/cidade_tiradentes_clip.wav?se=2025-05-20T03%3A15%3A08Z&sp=r&sv=2025-05-05&sr=b&sig=2K2a4vHNxJRNJ9Fc2QY/os9o3jgE0kcNx8qbCCjVPDk%3D', 'https://transcricoespdm.blob.core.windows.net/audios/perus_clip.wav?se=2025-05-20T03%3A15%3A41Z&sp=r&sv=2025-05-05&sr=b&sig=lq/gukuhPt8Ucvn/mnjYhdOqg1pelOem/7rLTkeV85o%3D', 'https://transcricoespdm.blob.core.windows.net/audios/cidade_ademar_clip.wav?se=2025-05-20T03%3A16%3A18Z&sp=r&sv=2025-05-05&sr=b&sig=UHkBx8VtljTY3GmdRdEx6y6lrBb1luyeBJwkYAJm6Fo%3D', 'https://transcricoespdm.blob.core.windows.net/audios/butanta_clip.wav?se=2025-05-20T03%3A16%3A26Z&sp=r&sv=2025-05-05&sr=b&sig=r4tMVu8%2BV9voiTazJ3bgHzigEAFHuTGSvnFpS3qKKIM%3D', 'https://transcricoespdm.blob.core.windows.net/audios/se_clip.wav?se=2025-05-20T03%3A16%3A46Z&sp=r&sv=2025-05-05&sr=b&sig=Mgymd/HsjnNe2LAOBchgZCf3wPTAXW6YeGQus2Ugwd4%3D', 'https://transcricoespdm.blob.core.windows.net/audios/pirituba_jaragua_clip.wav?se=2025-05-20T03%3A17%3A18Z&sp=r&sv=2025-05-05&sr=b&sig=nN0GmKORsqsdL6bRPL7j0hvY4VYxX3GxdXB3HOl5rUs%3D', 'https://transcricoespdm.blob.core.windows.net/audios/vila_mariana_clip.wav?se=2025-05-20T03%3A18%3A59Z&sp=r&sv=2025-05-05&sr=b&sig=kEzsViQA/JOzGMDo/keT6JEmLl6W3YrL9OsTFPRN7KA%3D', 'https://transcricoespdm.blob.core.windows.net/audios/jacana_tremembe_clip.wav?se=2025-05-20T03%3A19%3A48Z&sp=r&sv=2025-05-05&sr=b&sig=F6H4b9vqA71KrrR0F07ejSJsGbLSqnodT%2BsRS4W2XNw%3D', 'https://transcricoespdm.blob.core.windows.net/audios/guaianases_clip.wav?se=2025-05-20T03%3A20%3A41Z&sp=r&sv=2025-05-05&sr=b&sig=e6V3yh4Bd9p2/dCM8DhcShTB1ZtXSr%2Bk9KkGxGiDbds%3D', 'https://transcricoespdm.blob.core.windows.net/audios/santo_amaro_clip.wav?se=2025-05-20T03%3A21%3A01Z&sp=r&sv=2025-05-05&sr=b&sig=NJkAEw1OVZ1iMaL1bt40qSVc7lxQlqEb%2BkGOtOfxS7o%3D', 'https://transcricoespdm.blob.core.windows.net/audios/casa_verde_cachoeirinha_clip.wav?se=2025-05-20T03%3A22%3A03Z&sp=r&sv=2025-05-05&sr=b&sig=e5Og4Znkc7Lxiu3Y5m%2BMgZF46eZsmtbFpjMljJOBI68%3D', 'https://transcricoespdm.blob.core.windows.net/audios/itaquera_clip.wav?se=2025-05-20T03%3A23%3A14Z&sp=r&sv=2025-05-05&sr=b&sig=qgQ0Re8YjQ%2BMyQ23f18SnTNQdvCiChvHDFEdvGFlbfQ%3D', 'https://transcricoespdm.blob.core.windows.net/audios/jabaquara_clip.wav?se=2025-05-20T03%3A23%3A45Z&sp=r&sv=2025-05-05&sr=b&sig=tG6qYET1J%2BrNftGuyXwzPXS6HTM2tp2eSuHBeud6G/M%3D', 'https://transcricoespdm.blob.core.windows.net/audios/itaim_paulista_clip.wav?se=2025-05-20T03%3A24%3A22Z&sp=r&sv=2025-05-05&sr=b&sig=24DQI5ZtejHlTqhUzHGHjzg7tFvKvovL4y5zYsltp0c%3D', 'https://transcricoespdm.blob.core.windows.net/audios/ipiranga_clip.wav?se=2025-05-20T03%3A24%3A51Z&sp=r&sv=2025-05-05&sr=b&sig=N%2BbGDmyuRLrcbXyQAwbBgT/KH4zuWTZ5S9nfubg7r9o%3D', 'https://transcricoespdm.blob.core.windows.net/audios/parelheiros_clip.wav?se=2025-05-20T03%3A25%3A39Z&sp=r&sv=2025-05-05&sr=b&sig=sSiBCEzMvXoC4cPLYwlpG2ynusU7oW2EDk8uRy5ubtg%3D', 'https://transcricoespdm.blob.core.windows.net/audios/freguesia_brasilandia_clip.wav?se=2025-05-20T03%3A26%3A37Z&sp=r&sv=2025-05-05&sr=b&sig=lB0p0VT4whVXfJ5nsq%2BGkt4eusYaTG6/PZxnGJybU9s%3D', "https://transcricoespdm.blob.core.windows.net/audios/m'boi_mirim_clip.wav?se=2025-05-20T03%3A27%3A25Z&sp=r&sv=2025-05-05&sr=b&sig=W/JjAai/6jLTK%2B3Wz4cfN6Xa%2BR3VFg3DSvRzrA21%2BoI%3D", 'https://transcricoespdm.blob.core.windows.net/audios/mooca_clip.wav?se=2025-05-20T03%3A27%3A41Z&sp=r&sv=2025-05-05&sr=b&sig=2IcuHK2rWzCBbi5RWdcTMJA1Ig8JO%2Bzls1ZiBW1yZtI%3D', 'https://transcricoespdm.blob.core.windows.net/audios/sapopemba_clip.wav?se=2025-05-20T03%3A28%3A29Z&sp=r&sv=2025-05-05&sr=b&sig=jf4naWGGGcUXx%2BQ52P24wZNFXVTobT9lKJBn5jc8754%3D', 'https://transcricoespdm.blob.core.windows.net/audios/vila_prudente_clip.wav?se=2025-05-20T03%3A29%3A20Z&sp=r&sv=2025-05-05&sr=b&sig=PfRWzVAJdaHZeVcj4WM0Jbo4UrLguGbdwwGdO7KqYMc%3D', 'https://transcricoespdm.blob.core.windows.net/audios/penha_clip.wav?se=2025-05-20T03%3A30%3A00Z&sp=r&sv=2025-05-05&sr=b&sig=tIHB9asjhHsxkdaB/A/%2BvTnv%2BeOxCuJ69MElI8pk1kY%3D', 'https://transcricoespdm.blob.core.windows.net/audios/sao_mateus_clip.wav?se=2025-05-20T03%3A30%3A59Z&sp=r&sv=2025-05-05&sr=b&sig=7s8wjQk0QBW2Y2PV6qfe7/GHj1ueSa8/8hjXqCeznec%3D', 'https://transcricoespdm.blob.core.windows.net/audios/sao_miguel_clip.wav?se=2025-05-20T03%3A31%3A57Z&sp=r&sv=2025-05-05&sr=b&sig=c4p3equGm1vKmj77I1nbMxSzAGRzGMgjyOYQhobsvnY%3D']

In [21]:
transcritor.max_wait_seconds = 60 * 60 * 3
transcritor.wait_seconds = 60 * 5

In [ ]:
transcritor.monitorar()

🔍 Monitorando transcrições em andamento...
🧭 Status: Running
⏳ Ainda em processamento, reenfileirando...
🧭 Status: Running
⏳ Ainda em processamento, reenfileirando...
🧭 Status: Running
⏳ Ainda em processamento, reenfileirando...
🧭 Status: Running
⏳ Ainda em processamento, reenfileirando...
🧭 Status: Running
⏳ Ainda em processamento, reenfileirando...
🧭 Status: Running
⏳ Ainda em processamento, reenfileirando...
🧭 Status: Running
⏳ Ainda em processamento, reenfileirando...